language: node_js
node_js:
  - '4'
  - '5'
before_install:
  - 'npm install -g bower web-component-tester'
  - 'bower install'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script: 'wct'
